[build]
  command = "npm run build"
  publish = ".next"


# Optional: Redirect all requests to Next.js (including API routes)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200