[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: Redirect all requests to Next.js (including API routes)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200